// Code generated by github.com/swaggest/json-cli <version>, DO NOT EDIT.

// Package message contains JSON mapping structures.
package message

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"time"
)

// LightMeasuredPayload structure is generated from "#/components/schemas/lightMeasuredPayload".
type LightMeasuredPayload struct {
	Lumens               int64                  `json:"lumens,omitempty"` // Light intensity measured in lumens.
	SentAt               *time.Time             `json:"sentAt,omitempty"` // Date and time when the message was sent.
	AdditionalProperties map[string]interface{} `json:"-"`                // All unmatched properties
}

type marshalLightMeasuredPayload LightMeasuredPayload

var ignoreKeysLightMeasuredPayload = []string{
	"lumens",
	"sentAt",
}

// UnmarshalJSON decodes JSON.
func (i *LightMeasuredPayload) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalLightMeasuredPayload(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysLightMeasuredPayload {
		delete(m, key)
	}

	for key, rawValue := range m {
		if ii.AdditionalProperties == nil {
			ii.AdditionalProperties = make(map[string]interface{}, 1)
		}

		var val interface{}

		err = json.Unmarshal(rawValue, &val)
		if err != nil {
			return err
		}

		ii.AdditionalProperties[key] = val
	}

	*i = LightMeasuredPayload(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i LightMeasuredPayload) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalLightMeasuredPayload(i), i.AdditionalProperties)
}

// TurnOnOffPayload structure is generated from "#/components/schemas/turnOnOffPayload".
type TurnOnOffPayload struct {
	Command              TurnOnOffPayloadCommand `json:"command,omitempty"` // Whether to turn on or off the light.
	SentAt               *time.Time              `json:"sentAt,omitempty"`  // Date and time when the message was sent.
	AdditionalProperties map[string]interface{}  `json:"-"`                 // All unmatched properties
}

type marshalTurnOnOffPayload TurnOnOffPayload

var ignoreKeysTurnOnOffPayload = []string{
	"command",
	"sentAt",
}

// UnmarshalJSON decodes JSON.
func (i *TurnOnOffPayload) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalTurnOnOffPayload(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysTurnOnOffPayload {
		delete(m, key)
	}

	for key, rawValue := range m {
		if ii.AdditionalProperties == nil {
			ii.AdditionalProperties = make(map[string]interface{}, 1)
		}

		var val interface{}

		err = json.Unmarshal(rawValue, &val)
		if err != nil {
			return err
		}

		ii.AdditionalProperties[key] = val
	}

	*i = TurnOnOffPayload(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i TurnOnOffPayload) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalTurnOnOffPayload(i), i.AdditionalProperties)
}

// DimLightPayload structure is generated from "#/components/schemas/dimLightPayload".
type DimLightPayload struct {
	Percentage           uint8                  `json:"percentage,omitempty"` // Percentage to which the light should be dimmed to.
	SentAt               *time.Time             `json:"sentAt,omitempty"`     // Date and time when the message was sent.
	AdditionalProperties map[string]interface{} `json:"-"`                    // All unmatched properties
}

type marshalDimLightPayload DimLightPayload

var ignoreKeysDimLightPayload = []string{
	"percentage",
	"sentAt",
}

// UnmarshalJSON decodes JSON.
func (i *DimLightPayload) UnmarshalJSON(data []byte) error {
	var err error

	ii := marshalDimLightPayload(*i)

	err = json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	var m map[string]json.RawMessage

	err = json.Unmarshal(data, &m)
	if err != nil {
		m = nil
	}

	for _, key := range ignoreKeysDimLightPayload {
		delete(m, key)
	}

	for key, rawValue := range m {
		if ii.AdditionalProperties == nil {
			ii.AdditionalProperties = make(map[string]interface{}, 1)
		}

		var val interface{}

		err = json.Unmarshal(rawValue, &val)
		if err != nil {
			return err
		}

		ii.AdditionalProperties[key] = val
	}

	*i = DimLightPayload(ii)

	return nil
}

// MarshalJSON encodes JSON.
func (i DimLightPayload) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalDimLightPayload(i), i.AdditionalProperties)
}

// TurnOnOffPayloadCommand is an enum type.
type TurnOnOffPayloadCommand string

// TurnOnOffPayloadCommand values enumeration.
const (
	TurnOnOffPayloadCommandOn = TurnOnOffPayloadCommand("on")
	TurnOnOffPayloadCommandOff = TurnOnOffPayloadCommand("off")
)

// MarshalJSON encodes JSON.
func (i TurnOnOffPayloadCommand) MarshalJSON() ([]byte, error) {
	switch i {
	case TurnOnOffPayloadCommandOn:
	case TurnOnOffPayloadCommandOff:

	default:
		return nil, fmt.Errorf("unexpected TurnOnOffPayloadCommand value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *TurnOnOffPayloadCommand) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := TurnOnOffPayloadCommand(ii)

	switch v {
	case TurnOnOffPayloadCommandOn:
	case TurnOnOffPayloadCommandOff:

	default:
		return fmt.Errorf("unexpected TurnOnOffPayloadCommand value: %v", v)
	}

	*i = v

	return nil
}

func marshalUnion(maps ...interface{}) ([]byte, error) {
	result := make([]byte, 1, 100)
	result[0] = '{'
	isObject := true

	for _, m := range maps {
		j, err := json.Marshal(m)
		if err != nil {
			return nil, err
		}

		if string(j) == "{}" {
			continue
		}

		if string(j) == "null" {
			continue
		}

		if j[0] != '{' {
			if len(result) == 1 && (isObject || bytes.Equal(result, j)) {
				result = j
				isObject = false

				continue
			}

			return nil, errors.New("failed to union map: object expected, " + string(j) + " received")
		}

		if !isObject {
			return nil, errors.New("failed to union " + string(result) + " and " + string(j))
		}

		if len(result) > 1 {
			result[len(result)-1] = ','
		}

		result = append(result, j[1:]...)
	}

	// Close empty result.
	if isObject && len(result) == 1 {
		result = append(result, '}')
	}

	return result, nil
}
