// Code generated by github.com/swaggest/json-cli <version>, DO NOT EDIT.

// Package message contains JSON mapping structures.
package message

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

// LightMeasuredPayload structure is generated from "#/components/schemas/lightMeasuredPayload".
type LightMeasuredPayload struct {
	Lumens               int64                  `json:"lumens,omitempty"` // Light intensity measured in lumens.
	SentAt               *time.Time             `json:"sentAt,omitempty"` // Date and time when the message was sent.
	AdditionalProperties map[string]interface{} `json:"-"`                // All unmatched properties
}

type marshalLightMeasuredPayload LightMeasuredPayload

// UnmarshalJSON decodes JSON.
func (i *LightMeasuredPayload) UnmarshalJSON(data []byte) error {
	ii := marshalLightMeasuredPayload(*i)

	err := unionMap{
		mustUnmarshal: []interface{}{&ii},
		ignoreKeys: []string{
			"lumens",
			"sentAt",
		},
		additionalProperties: &ii.AdditionalProperties,
		jsonData: data,
	}.unmarshal()

	if err != nil {
		return err
	}

	*i = LightMeasuredPayload(ii)

	return err
}

// MarshalJSON encodes JSON.
func (i LightMeasuredPayload) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalLightMeasuredPayload(i), i.AdditionalProperties)
}

// TurnOnOffPayload structure is generated from "#/components/schemas/turnOnOffPayload".
type TurnOnOffPayload struct {
	Command              TurnOnOffPayloadCommand `json:"command,omitempty"` // Whether to turn on or off the light.
	SentAt               *time.Time              `json:"sentAt,omitempty"`  // Date and time when the message was sent.
	AdditionalProperties map[string]interface{}  `json:"-"`                 // All unmatched properties
}

type marshalTurnOnOffPayload TurnOnOffPayload

// UnmarshalJSON decodes JSON.
func (i *TurnOnOffPayload) UnmarshalJSON(data []byte) error {
	ii := marshalTurnOnOffPayload(*i)

	err := unionMap{
		mustUnmarshal: []interface{}{&ii},
		ignoreKeys: []string{
			"command",
			"sentAt",
		},
		additionalProperties: &ii.AdditionalProperties,
		jsonData: data,
	}.unmarshal()

	if err != nil {
		return err
	}

	*i = TurnOnOffPayload(ii)

	return err
}

// MarshalJSON encodes JSON.
func (i TurnOnOffPayload) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalTurnOnOffPayload(i), i.AdditionalProperties)
}

// DimLightPayload structure is generated from "#/components/schemas/dimLightPayload".
type DimLightPayload struct {
	Percentage           uint8                  `json:"percentage,omitempty"` // Percentage to which the light should be dimmed to.
	SentAt               *time.Time             `json:"sentAt,omitempty"`     // Date and time when the message was sent.
	AdditionalProperties map[string]interface{} `json:"-"`                    // All unmatched properties
}

type marshalDimLightPayload DimLightPayload

// UnmarshalJSON decodes JSON.
func (i *DimLightPayload) UnmarshalJSON(data []byte) error {
	ii := marshalDimLightPayload(*i)

	err := unionMap{
		mustUnmarshal: []interface{}{&ii},
		ignoreKeys: []string{
			"percentage",
			"sentAt",
		},
		additionalProperties: &ii.AdditionalProperties,
		jsonData: data,
	}.unmarshal()

	if err != nil {
		return err
	}

	*i = DimLightPayload(ii)

	return err
}

// MarshalJSON encodes JSON.
func (i DimLightPayload) MarshalJSON() ([]byte, error) {
	return marshalUnion(marshalDimLightPayload(i), i.AdditionalProperties)
}

// TurnOnOffPayloadCommand is an enum type.
type TurnOnOffPayloadCommand string

// TurnOnOffPayloadCommand values enumeration.
const (
	TurnOnOffPayloadCommandOn = TurnOnOffPayloadCommand("on")
	TurnOnOffPayloadCommandOff = TurnOnOffPayloadCommand("off")
)

// MarshalJSON encodes JSON.
func (i TurnOnOffPayloadCommand) MarshalJSON() ([]byte, error) {
	switch i {
	case TurnOnOffPayloadCommandOn:
	case TurnOnOffPayloadCommandOff:

	default:
		return nil, fmt.Errorf("unexpected TurnOnOffPayloadCommand value: %v", i)
	}

	return json.Marshal(string(i))
}

// UnmarshalJSON decodes JSON.
func (i *TurnOnOffPayloadCommand) UnmarshalJSON(data []byte) error {
	var ii string

	err := json.Unmarshal(data, &ii)
	if err != nil {
		return err
	}

	v := TurnOnOffPayloadCommand(ii)

	switch v {
	case TurnOnOffPayloadCommandOn:
	case TurnOnOffPayloadCommandOff:

	default:
		return fmt.Errorf("unexpected TurnOnOffPayloadCommand value: %v", v)
	}

	*i = v

	return nil
}

func marshalUnion(maps ...interface{}) ([]byte, error) {
	result := make([]byte, 1, 100)
	result[0] = '{'
	isObject := true

	for _, m := range maps {
		j, err := json.Marshal(m)
		if err != nil {
			return nil, err
		}

		if string(j) == "{}" {
			continue
		}

		if string(j) == "null" {
			continue
		}

		if j[0] != '{' {
			if len(result) == 1 && (isObject || bytes.Equal(result, j)) {
				result = j
				isObject = false

				continue
			}

			return nil, errors.New("failed to union map: object expected, " + string(j) + " received")
		}

		if !isObject {
			return nil, errors.New("failed to union " + string(result) + " and " + string(j))
		}

		if len(result) > 1 {
			result[len(result)-1] = ','
		}

		result = append(result, j[1:]...)
	}

	// Close empty result.
	if isObject && len(result) == 1 {
		result = append(result, '}')
	}

	return result, nil
}
type unionMap struct {
	mustUnmarshal        []interface{}
	ignoreKeys           []string
	additionalProperties interface{}
	jsonData             []byte
}

func (u unionMap) unmarshal() error {
	for _, item := range u.mustUnmarshal {
		// Unmarshal to struct.
		err := json.Unmarshal(u.jsonData, item)
		if err != nil {
			return err
		}
	}

	if u.additionalProperties == nil {
		return nil
	}

	// Unmarshal to a generic map.
	var m map[string]*json.RawMessage

	err := json.Unmarshal(u.jsonData, &m)
	if err != nil {
		return err
	}

	// Remove ignored keys (defined in struct).
	for _, i := range u.ignoreKeys {
		delete(m, i)
	}

	// Return early on empty map.
	if len(m) == 0 {
		return nil
	}

	if u.additionalProperties != nil {
		return u.unmarshalAdditionalProperties(m)
	}

	return nil
}

func (u unionMap) unmarshalAdditionalProperties(m map[string]*json.RawMessage) error {
	var err error

	subMap := make([]byte, 1, 100)

	subMap[0] = '{'

	// Iterating map and filling additional properties.
	for key, val := range m {
		keyEscaped := `"` + strings.Replace(key, `"`, `\"`, -1) + `":`

		if len(subMap) != 1 {
			subMap = append(subMap[:len(subMap)-1], ',')
		}

		subMap = append(subMap, []byte(keyEscaped)...)

		if val != nil {
			subMap = append(subMap, []byte(*val)...)
		} else {
			subMap = append(subMap, []byte("null")...)
		}

		subMap = append(subMap, '}')
	}

	if len(subMap) > 1 {
		err = json.Unmarshal(subMap, u.additionalProperties)
		if err != nil {
			return err
		}
	}

	return nil
}
