<?php

namespace Swaggest\JsonCli;


use Swaggest\GoCodeBuilder\JsonSchema\GoBuilder;
use Swaggest\GoCodeBuilder\JsonSchema\StructHookCallback;
use Swaggest\GoCodeBuilder\Templates\GoFile;
use Swaggest\GoCodeBuilder\Templates\Struct\StructDef;
use Swaggest\JsonSchema\Context;
use Swaggest\JsonSchema\RemoteRef\Preloaded;
use Swaggest\JsonSchema\Schema;
use Yaoi\Command;

class GenGo extends Command
{
    /** @var string */
    public $schema;
    /** @var string */
    public $packageName = 'entities';
    /** @var string */
    public $rootName = 'Structure';
    /** @var bool */
    public $showConstProperties = false;
    /** @var bool */
    public $keepParentInPropertyNames = false;
    /** @var []string */
    public $defPtr;
    /** @var []string */
    public $ptrInSchema;


    /**
     * @param Command\Definition $definition
     * @param \stdClass|static $options
     */
    public static function setUpDefinition(Command\Definition $definition, $options)
    {
        $definition->description = 'Generate Go code from JSON schema, output to STDOUT';
        $options->schema = Command\Option::create()
            ->setDescription('Path to JSON schema file')->setIsUnnamed()->setIsRequired();

        $options->ptrInSchema = Command\Option::create()->setType()->setIsVariadic()
            ->setDescription('JSON pointer to structure in in root schema, default #');

        $options->packageName = Command\Option::create()->setType()
            ->setDescription('Go package name, default "entities"');

        $options->rootName = Command\Option::create()->setType()
            ->setDescription('Go root struct name, default "Structure"');

        $options->defPtr = Command\Option::create()->setType()->setIsVariadic()
            ->setDescription('Definitions pointer, default #/definitions');

        $options->showConstProperties = Command\Option::create()
            ->setDescription('Show properties with constant values, hidden by default');

        $options->keepParentInPropertyNames = Command\Option::create()
            ->setDescription('Keep parent prefix in property name, removed by default');

    }


    public function performAction()
    {


        $dataValue = Base::readJsonOrYaml($this->schema, $this->response);
        if (!$dataValue) {
            $this->response->error('Unable to find schema in ' . $this->schema);
            die(1);
        }

        $skipRoot = false;
        if (empty($this->ptrInSchema)) {
            $schema = Schema::import($dataValue);
        } else {
            $skipRoot = true;
            $preloaded = new Preloaded();
            $preloaded->setSchemaData($this->schema, $dataValue);
            $data = new \stdClass();
            foreach ($this->ptrInSchema as $i => $ptr) {
                $data->oneOf[$i] = (object)[Schema::PROP_REF => $this->schema . $ptr];
            }
            $schema = Schema::import($data, new Context($preloaded));
        }

        $builder = new GoBuilder();
        $builder->options->hideConstProperties = !$this->showConstProperties;
        $builder->options->trimParentFromPropertyNames = !$this->keepParentInPropertyNames;
        if (!empty($this->defPtr)) {
            foreach ($this->defPtr as $defPtr) {
                $builder->pathToNameHook->prefixes[] = $defPtr;
            }
        }
        $builder->structCreatedHook = new StructHookCallback(function (StructDef $structDef, $path, $schema) use ($builder) {
            if ('#' === $path) {
                $structDef->setName($this->rootName);
            }
        });
        $builder->getType($schema);

        $goFile = new GoFile($this->packageName);
        $goFile->fileComment = 'Code generated by github.com/swaggest/json-cli, DO NOT EDIT.';
        $goFile->setComment('Package ' . $this->packageName . ' contains JSON mapping structures.');
        foreach ($builder->getGeneratedStructs() as $generatedStruct) {
            if ($skipRoot && $generatedStruct->path === '#') {
                continue;
            }
            $goFile->getCode()->addSnippet($generatedStruct->structDef);
        }
        $goFile->getCode()->addSnippet($builder->getCode());

        echo $goFile->render();
    }
}